### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by 10maysingh** [MSTC-DA-IICT/Hacktoberfest24-Routinr-Flutter#2]
Design a beautiful profile page which shows things like username, email, and profile picture and many more.

**Comment by nycanshu** [comment]
I want to contribute on this issue please assign under hacktoberfest24

**Comment by 10maysingh** [comment]
You have already been assigned another task. Kindly complete that first before proceeding to this issue.

**Comment by prxjwal** [comment]
I want to contribute could you assign this to me

**Comment by dhyey2075** [comment]
Ok you have been assigned this issue. Also add options for logout or sign in based on the current log in status of user.
