### ISSUE TITLE
Change app logo

### ISSUE THREAD

**Issue by 10maysingh** [MSTC-DA-IICT/Hacktoberfest24-Routinr-Flutter#5]
Change the Logo of the app. By default, you will get the Flutter logo when running the app but you must change the logo according to the app name.

**Comment by SATTIRAMYASRI** [comment]
I’m participating in Hacktoberfest and saw the issue about changing the app logo. Could you clarify if you have a specific logo (PNG or JPEG) to use, or should I create my own? If possible, could you assign this issue to me?

**Comment by 10maysingh** [comment]
You should design any specific logo which reflects the essence of the app's name "Routinr". Ok, you will be assigned this issue.

**Comment by dhyey2075** [comment]
dart: ">=3.5.3 <4.0.0"
flutter: ">=3.18.0-18.0.pre.54"

**Comment by 10maysingh** [comment]
Well done! You can go with this logo. The versions of the technologies have been given above for your reference.

**Comment by SATTIRAMYASRI** [comment]
ok thanks i  will change the app logo and will let you know

**Comment by 10maysingh** [comment]
@SATTIRAMYASRI its been a week since you got assigned this issue. You have 1 more day to complete this issue.

**Comment by SATTIRAMYASRI** [comment]
@10maysingh sorry i have issue with my laptop.so that's why i am not able to complete it.please give me 4 to 5 days. once my system is working fine i will complete it asap

**Comment by SATTIRAMYASRI** [comment]
@10maysingh @dhyey2075 I've raised the pull request for the new logo update. Please review it at your earliest convenience and merge it if everything looks good. Thank you!
